### ISSUE TITLE
API location?

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [EntJavaTeamProj/TeamProjOnline#3]
Good morning! @ScarletIvy @AshleyNWagner @eburzlaff @Mlor10  Two things:

1. I do not see a response to the first issue here regarding scope of your RESTful API.
2.  At this point, it appears that your application is a web application rather than a RESTful API. Remember that the goal of this project is to create a RESTful API similar to the week 9 activities and exercise.

**Comment by Mlor10** [comment]
@pawaitemadisoncollege 
Our team has reviewed week 9 activities/exercise and have implemented it in our team project. Thank you for pointing out that our project was more of a web application than a RESTful API. We are now on the right track in making a RESTful API. Also, we have responded to the first issue regarding the scope of our RESTful API.
